# Importing Dependencies

In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text
from IPython.display import display

# Data Cleaning and Preperation

In [129]:
df = pd.read_csv("CreditScoring.csv")

In [130]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [131]:
df.columns = df.columns.str.lower()

In [132]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [133]:
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unk'
}

df.status = df.status.map(status_values)

In [134]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,1,60,30,2,1,3,73,129,0,0,800,846
1,ok,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,default,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,ok,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,ok,0,1,36,26,1,1,1,46,107,0,0,310,910

In [135]:
home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

df.home = df.home.map(home_values)

marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

df.marital = df.marital.map(marital_values)

records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

df.records = df.records.map(records_values)

job_values = {
    1: 'fixed',
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

df.job = df.job.map(job_values)

In [136]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [137]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,763317.0,1060341.0,404382.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,8703625.0,10217569.0,6344253.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3500.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,166.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,99999999.0,99999999.0,99999999.0,5000.0,11140.0

In [138]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)

In [139]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4421.0,4408.0,4437.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,131.0,5403.0,343.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,86.0,11573.0,1246.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3000.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,165.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,959.0,300000.0,30000.0,5000.0,11140.0

In [140]:
df = df[df.status != 'unk'].reset_index(drop=True)

# Model Train Test Split

In [141]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=11)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=11)

In [142]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [143]:
y_train = (df_train.status == 'default').astype('int').values
y_val = (df_val.status == 'default').astype('int').values
y_test = (df_test.status == 'default').astype('int').values

In [144]:
del df_train['status']
del df_val['status']
del df_test['status']

In [145]:
df_train

,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,10,owner,36,36,married,no,freelance,75,0.0,10000.0,0.0,1000,1400
1,6,parents,48,32,single,yes,fixed,35,85.0,0.0,0.0,1100,1330
2,1,parents,48,40,married,no,fixed,75,121.0,0.0,0.0,1320,1600
3,1,parents,48,23,single,no,partime,35,72.0,0.0,0.0,1078,1079
4,5,owner,36,46,married,no,freelance,60,100.0,4000.0,0.0,1100,1897
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,18,private,36,45,married,no,fixed,45,220.0,20000.0,0.0,800,1600
2668,7,private,60,29,married,no,fixed,60,51.0,3500.0,500.0,1000,1290
2669,1,parents,24,19,single,no,fixed,35,28.0,0.0,0.0,400,600
2670,15,owner,48,43,married,no,freelance,60,100.0,18000.0,0.0,2500,2976
2671,12,owner,48,27,married,yes,fixed,45,110.0,5000.0,1300.0,450,1636

# Decision Trees

In [146]:
def assess_risk(client):
    if client['records'] == 'yes':
        if client['job'] == 'parttime':
            return 'default'
        else:
            return 'ok'
    else:
        if client['assets'] > 6000:
            return 'ok'
        else:
            return 'default'

In [147]:
xi = df_train.iloc[500].to_dict()

In [148]:
xi

{'seniority': 15,
 'home': 'owner',
 'time': 24,
 'age': 41,
 'marital': 'married',
 'records': 'yes',
 'job': 'partime',
 'expenses': 45,
 'income': 180.0,
 'assets': 6000.0,
 'debt': 0.0,
 'amount': 700,
 'price': 1888}

In [149]:
assess_risk(xi)

'ok'

In [150]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

In [151]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [152]:
X_train

array([[3.60e+01, 1.00e+03, 1.00e+04, ..., 0.00e+00, 1.00e+01, 3.60e+01],
       [3.20e+01, 1.10e+03, 0.00e+00, ..., 1.00e+00, 6.00e+00, 4.80e+01],
       [4.00e+01, 1.32e+03, 0.00e+00, ..., 0.00e+00, 1.00e+00, 4.80e+01],
       ...,
       [1.90e+01, 4.00e+02, 0.00e+00, ..., 0.00e+00, 1.00e+00, 2.40e+01],
       [4.30e+01, 2.50e+03, 1.80e+04, ..., 0.00e+00, 1.50e+01, 4.80e+01],
       [2.70e+01, 4.50e+02, 5.00e+03, ..., 1.00e+00, 1.20e+01, 4.80e+01]],
      shape=(2672, 29))

In [153]:
dv.get_feature_names_out()

array(['age', 'amount', 'assets', 'debt', 'expenses', 'home=ignore',
       'home=other', 'home=owner', 'home=parents', 'home=private',
       'home=rent', 'home=unk', 'income', 'job=fixed', 'job=freelance',
       'job=others', 'job=partime', 'job=unk', 'marital=divorced',
       'marital=married', 'marital=separated', 'marital=single',
       'marital=unk', 'marital=widow', 'price', 'records=no',
       'records=yes', 'seniority', 'time'], dtype=object)

In [154]:
dt = DecisionTreeClassifier(max_depth=3)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [155]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [156]:
y_pred = dt.predict_proba(X_train)[:, 1]
auc = roc_auc_score(y_train, y_pred)
print('train:', auc)

y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print('val:', auc)

train: 0.7761016984958594
val: 0.7389079944782155

In [157]:
print(export_text(dt, feature_names=dv.get_feature_names_out()))

|--- records=no <= 0.50
|   |--- seniority <= 6.50
|   |   |--- amount <= 862.50
|   |   |   |--- class: 0
|   |   |--- amount >  862.50
|   |   |   |--- class: 1
|   |--- seniority >  6.50
|   |   |--- income <= 103.50
|   |   |   |--- class: 1
|   |   |--- income >  103.50
|   |   |   |--- class: 0
|--- records=no >  0.50
|   |--- job=partime <= 0.50
|   |   |--- income <= 74.50
|   |   |   |--- class: 0
|   |   |--- income >  74.50
|   |   |   |--- class: 0
|   |--- job=partime >  0.50
|   |   |--- assets <= 8750.00
|   |   |   |--- class: 1
|   |   |--- assets >  8750.00
|   |   |   |--- class: 0

# Decision Tree Learning Algorithm

In [158]:
data = [
    [8000, 'default'],
    [2000, 'default'],
    [0, 'default'],
    [5000, 'ok'],
    [5000, 'ok'],
    [4000, 'ok'],
    [9000, 'ok'],
    [3000, 'default'],
]

df_example = pd.DataFrame(data, columns=['assets','status'])
df_example

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

In [159]:
df_example.sort_values('assets')

   assets   status
2       0  default
1    2000  default
7    3000  default
5    4000       ok
4    5000       ok
3    5000       ok
0    8000  default
6    9000       ok

In [160]:
Ts = [0, 2000, 3000, 4000, 5000, 8000]

In [161]:
for T in Ts:
    print(T)
    df_left = df_example [df_example.assets <= T]
    df_right = df_example [df_example.assets > T]

    display(df_left)
    print(df_left.status.value_counts(normalize=True))
    display(df_right)
    print(df_right.status.value_counts(normalize=True))
    print()

0

   assets   status
2       0  default

status
default    1.0
Name: proportion, dtype: float64

   assets   status
0    8000  default
1    2000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64

2000

   assets   status
1    2000  default
2       0  default

status
default    1.0
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64

3000

   assets   status
1    2000  default
2       0  default
7    3000  default

status
default    1.0
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok

status
ok         0.8
default    0.2
Name: proportion, dtype: float64

4000

   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok

status
ok         0.75
default    0.25
Name: proportion, dtype: float64

5000

   assets   status
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

   assets   status
0    8000  default
6    9000       ok

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

8000

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default

status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64

   assets status
6    9000     ok

status
ok    1.0
Name: proportion, dtype: float64

In [162]:
data = [
    [8000, 3000, 'default'],
    [2000, 1000, 'default'],
    [0, 1000, 'default'],
    [5000, 1000, 'ok'],
    [5000, 1000, 'ok'],
    [4000, 1000, 'ok'],
    [9000, 500, 'ok'],
    [3000, 2000, 'default'],
]

df_example = pd.DataFrame(data, columns=['assets', 'debt', 'status'])
df_example

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

In [163]:
df_example.sort_values('debt')

   assets  debt   status
6    9000   500       ok
1    2000  1000  default
3    5000  1000       ok
2       0  1000  default
5    4000  1000       ok
4    5000  1000       ok
7    3000  2000  default
0    8000  3000  default

In [164]:
thresholds = {
    'assets': [0, 2000, 3000, 4000, 5000, 8000],
    'debt': [500, 1000, 2000, 3000]
}

In [165]:
for feature, Ts in thresholds.items():
    print('################')
    print(feature)
    for T in Ts:
        print(T)
        df_left = df_example [df_example[feature] <= T]
        df_right = df_example [df_example[feature] > T]

        display(df_left)
        print(df_left.status.value_counts(normalize=True))
        display(df_right)
        print(df_right.status.value_counts(normalize=True))
        print()

################
assets
0

   assets  debt   status
2       0  1000  default

status
default    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64

2000

   assets  debt   status
1    2000  1000  default
2       0  1000  default

status
default    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64

3000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
7    3000  2000  default

status
default    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok

status
ok         0.8
default    0.2
Name: proportion, dtype: float64

4000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
5    4000  1000       ok
7    3000  2000  default

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
3    5000  1000       ok
4    5000  1000       ok
6    9000   500       ok

status
ok         0.75
default    0.25
Name: proportion, dtype: float64

5000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
7    3000  2000  default

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
6    9000   500       ok

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

8000

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
7    3000  2000  default

status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64

   assets  debt status
6    9000   500     ok

status
ok    1.0
Name: proportion, dtype: float64

################
debt
500

   assets  debt status
6    9000   500     ok

status
ok    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
7    3000  2000  default

status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64

1000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok

status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
7    3000  2000  default

status
default    1.0
Name: proportion, dtype: float64

2000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default

status
default    1.0
Name: proportion, dtype: float64

3000

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

Empty DataFrame
Columns: [assets, debt, status]
Index: []

Series([], Name: proportion, dtype: float64)

# Decision Trees Parameret Tuning

In [166]:
for d in [1, 2, 3, 4, 5, 6, 10, 15, 20, None]:
    dt = DecisionTreeClassifier(max_depth=d)
    dt.fit(X_train, y_train)

    y_pred = dt.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_pred)

    print('%4s -> %.3f' % (d, auc))

   1 -> 0.606
   2 -> 0.669
   3 -> 0.739
   4 -> 0.761
   5 -> 0.766
   6 -> 0.762
  10 -> 0.680
  15 -> 0.661

  20 -> 0.656
None -> 0.665

In [167]:
scores = []

for d in [4, 5, 6]:
    for s in [1, 2, 5, 10, 15, 20, 100, 200, 500]:
        dt = DecisionTreeClassifier(max_depth=d, min_samples_leaf=s)
        dt.fit(X_train, y_train)

        y_pred = dt.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_pred)

        scores.append((d,s, auc))

In [168]:
columns = ['max_depth', 'min_sample_leaf', 'auc']

df_scores = pd.DataFrame(scores, columns=columns)
df_scores.head()

   max_depth  min_sample_leaf       auc
0          4                1  0.761283
1          4                2  0.761283
2          4                5  0.761283
3          4               10  0.761283
4          4               15  0.763726

In [169]:
df_scores.sort_values(by='auc', ascending=False).head()

    max_depth  min_sample_leaf       auc
22          6               15  0.785474
21          6               10  0.777803
24          6              100  0.776434
23          6               20  0.773634
14          5               20  0.773537

In [170]:
df_scores

    max_depth  min_sample_leaf       auc
0           4                1  0.761283
1           4                2  0.761283
2           4                5  0.761283
3           4               10  0.761283
4           4               15  0.763726
5           4               20  0.760910
6           4              100  0.755937
7           4              200  0.747260
8           4              500  0.679842
9           5                1  0.766496
10          5                2  0.766938
11          5                5  0.767755
12          5               10  0.762276
13          5               15  0.772405
14          5               20  0.773537
15          5              100  0.763384
16          5              200  0.759073
17          5              500  0.679842
18          6                1  0.753315
19          6                2  0.750094
20          6                5  0.761552
21          6               10  0.777803
22          6               15  0.785474
23          6               20  0.773634
24          6              100  0.776434
25          6              200  0.768267
26          6              500  0.679842